repos:
  # Mypy check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v2.3.1"
    hooks:
      - id: mypy
        types: [ python ]
        exclude: "alembic/|tests/"

  # Linting with --fix and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  # Check uv.lock
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.9
    hooks:
      - id: uv-lock
