[project]
name = "app"
version = "0.1.0"
description = "Agregator API for Events Provider API"
readme = "README.md"
authors = [
    { name = "Iadzhak Sergei", email = "yadzhak@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]


[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"


[tools.fastapi]
entrypoint = "src.app.main:app"