"""tabe ticket rename ticket_id to id

Revision ID: 1801a95cafb5
Revises: fb47f2eb9796
Create Date: 2026-09-07 23:19:28.970422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1801a95cafb5'
down_revision: Union[str, Sequence[str], None] = 'fb47f2eb9796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_column('ticket', 'ticket_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('ticket', 'id')
    # ### end Alembic commands ###
