"""add col seat to ticket table

Revision ID: 57fbe3593d13
Revises: c1619a4ec6b3
Create Date: 2026-09-07 16:10:58.692769

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '57fbe3593d13'
down_revision: str | Sequence[str] | None = 'c1619a4ec6b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('seat', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'seat')
    # ### end Alembic commands ###
