"""change table tickets

Revision ID: 73426b5f6d59
Revises: 57fbe3593d13
Create Date: 2026-09-07 16:23:16.579251

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '73426b5f6d59'
down_revision: str | Sequence[str] | None = '57fbe3593d13'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ticket', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ticket', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('ticket', 'sold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('sold', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('ticket', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ticket', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ticket', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
