"""fix col name in event

Revision ID: 7cab3847ac00
Revises: 8211fa9ef6f8
Create Date: 2026-09-05 22:49:03.485029

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7cab3847ac00'
down_revision: str | Sequence[str] | None = '8211fa9ef6f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('event', 'staus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('staus', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('event', 'status')
    # ### end Alembic commands ###
