"""ticket add status

Revision ID: b870d00b7d02
Revises: e20dffcb4488
Create Date: 2026-10-02 13:46:39.812281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b870d00b7d02'
down_revision: Union[str, Sequence[str], None] = 'e20dffcb4488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'status')
    # ### end Alembic commands ###
