"""event, place tables

Revision ID: c9f8d9a58d58
Revises: 0f2be8f50842
Create Date: 2026-09-05 21:52:03.362104

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c9f8d9a58d58'
down_revision: str | Sequence[str] | None = '0f2be8f50842'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('seats_pattern', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(), nullable=False),
    sa.Column('staus', sa.String(), nullable=False),
    sa.Column('number_of_visitors', sa.Integer(), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('place')
    # ### end Alembic commands ###
