"""table ticket remove redudant id and constraint

Revision ID: fb47f2eb9796
Revises: 7907193a8661
Create Date: 2026-09-07 23:16:16.366614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb47f2eb9796'
down_revision: Union[str, Sequence[str], None] = '7907193a8661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_event_tickets'), 'ticket', type_='unique')
    op.drop_column('ticket', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('uq_event_tickets'), 'ticket', ['ticket_id', 'event_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
